package com.devcentre.tube.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StationsByLine {
	
public static final Map<String, List<Station>> stationsByLine = createMap();
	
	private static Map<String, List<Station>> createMap() {
		Map<String, List<Station>> map = new HashMap<String, List<Station>>();
		
		List<Station> bakerlooLineStations = new ArrayList<Station>();
		bakerlooLineStations.add(new Station("BST", "Baker Street"));
		bakerlooLineStations.add(new Station("CHX", "Charing Cross"));
		bakerlooLineStations.add(new Station("ERB", "Edgware Road"));
		bakerlooLineStations.add(new Station("ELE", "Elephant and Castle"));
		bakerlooLineStations.add(new Station("EMB", "Embankment"));
		bakerlooLineStations.add(new Station("HSD", "Harlesden"));
		bakerlooLineStations.add(new Station("HAW", "Harrow and Wealdstone"));
		bakerlooLineStations.add(new Station("KGN", "Kensal Green"));
		bakerlooLineStations.add(new Station("KNT", "Kenton"));
		bakerlooLineStations.add(new Station("KPK", "Kilburn Park"));
		bakerlooLineStations.add(new Station("LAM", "Lambeth North"));
		bakerlooLineStations.add(new Station("MDV", "Maida Vale"));
		bakerlooLineStations.add(new Station("MYB", "Marylebone"));
		bakerlooLineStations.add(new Station("NWM", "North Wembley"));
		bakerlooLineStations.add(new Station("OXC", "Oxford Circus"));
		bakerlooLineStations.add(new Station("PAD", "Paddington"));
		bakerlooLineStations.add(new Station("PIC", "Piccadilly Circus"));
		bakerlooLineStations.add(new Station("QPK", "Queen's Park"));
		bakerlooLineStations.add(new Station("RPK", "Regent's Park"));
		bakerlooLineStations.add(new Station("SKT", "South Kenton"));
		bakerlooLineStations.add(new Station("SPK", "Stonebridge Park"));
		bakerlooLineStations.add(new Station("WAR", "Warwick Avenue"));
		bakerlooLineStations.add(new Station("WLO", "Waterloo"));
		bakerlooLineStations.add(new Station("WEM", "Wembley Central"));
		bakerlooLineStations.add(new Station("WJN", "Willesden Junction"));
		map.put("B", bakerlooLineStations);
        
		List<Station> centralLineStations = new ArrayList<Station>();
		centralLineStations.add(new Station("BNK","Bank"));
		centralLineStations.add(new Station("BDE","Barkingside"));
		centralLineStations.add(new Station("BNG","Bethnal Green"));
		centralLineStations.add(new Station("BDS","Bond Street"));
		centralLineStations.add(new Station("BHL","Buckhurst Hill"));
		centralLineStations.add(new Station("CYL","Chancery Lane"));
		centralLineStations.add(new Station("CHG","Chigwell"));
		centralLineStations.add(new Station("DEB","Debden"));
		centralLineStations.add(new Station("EBY","Ealing Broadway"));
		centralLineStations.add(new Station("EAC","East Acton"));
		centralLineStations.add(new Station("EPP","Epping"));
		centralLineStations.add(new Station("FLP","Fairlop"));
		centralLineStations.add(new Station("GHL","Gants Hill"));
		centralLineStations.add(new Station("GRH","Grange Hill"));
		centralLineStations.add(new Station("GFD","Greenford"));
		centralLineStations.add(new Station("HAI","Hainault"));
		centralLineStations.add(new Station("HLN","Hanger Lane"));
		centralLineStations.add(new Station("HOL","Holborn"));
		centralLineStations.add(new Station("HPK","Holland Park"));
		centralLineStations.add(new Station("LAN","Lancaster Gate"));
		centralLineStations.add(new Station("LEY","Leyton"));
		centralLineStations.add(new Station("LYS","Leytonstone"));
		centralLineStations.add(new Station("LST","Liverpool Street"));
		centralLineStations.add(new Station("LTN","Loughton"));
		centralLineStations.add(new Station("MAR","Marble Arch"));
		centralLineStations.add(new Station("MLE","Mile End"));
		centralLineStations.add(new Station("NEP","Newbury Park"));
		centralLineStations.add(new Station("NAC","North Acton"));
		centralLineStations.add(new Station("NHT","Northolt"));
		centralLineStations.add(new Station("NHG","Notting Hill Gate"));
		centralLineStations.add(new Station("OXC","Oxford Circus"));
		centralLineStations.add(new Station("PER","Perivale"));
		centralLineStations.add(new Station("QWY","Queensway"));
		centralLineStations.add(new Station("RED","Redbridge"));
		centralLineStations.add(new Station("ROD","Roding Valley"));
		centralLineStations.add(new Station("RUG","Ruislip Gardens"));
		centralLineStations.add(new Station("SBC","Shepherd’s Bush"));
		centralLineStations.add(new Station("SNB","Snaresbrook"));
		centralLineStations.add(new Station("SRP","South Ruislip"));
		centralLineStations.add(new Station("SWF","South Woodford"));
		centralLineStations.add(new Station("STP","St Paul’s"));
		centralLineStations.add(new Station("SFD","Stratford"));
		centralLineStations.add(new Station("THB","Theydon Bois"));
		centralLineStations.add(new Station("TCR","Tottenham Court Road"));
		centralLineStations.add(new Station("WAN","Wanstead"));
		centralLineStations.add(new Station("WAC","West Acton"));
		centralLineStations.add(new Station("WRP","West Ruislip"));
		centralLineStations.add(new Station("WCT","White City"));
		centralLineStations.add(new Station("WFD","Woodford"));
		map.put("C", centralLineStations);
		
		List<Station> districtLineStations = new ArrayList<Station>();
		districtLineStations.add(new Station("ACT","Acton Town"));
		districtLineStations.add(new Station("ALE","Aldgate East"));
		districtLineStations.add(new Station("BKG","Barking"));
		districtLineStations.add(new Station("BCT","Barons Court"));
		districtLineStations.add(new Station("BEC","Becontree"));
		districtLineStations.add(new Station("BLF","Blackfriars"));
		districtLineStations.add(new Station("BWR","Bow Road"));
		districtLineStations.add(new Station("BBB","Bromley-by-Bow"));
		districtLineStations.add(new Station("CST","Cannon Street"));
		districtLineStations.add(new Station("CHP","Chiswick Park"));
		districtLineStations.add(new Station("DGE","Dagenham East"));
		districtLineStations.add(new Station("DGH","Dagenham Heathway"));
		districtLineStations.add(new Station("EBY","Ealing Broadway"));
		districtLineStations.add(new Station("ECM","Ealing Common"));
		districtLineStations.add(new Station("ECT","Earl’s Court"));
		districtLineStations.add(new Station("EHM","East Ham"));
		districtLineStations.add(new Station("EPY","East Putney"));
		districtLineStations.add(new Station("ERD","Edgware Road"));
		districtLineStations.add(new Station("EPK","Elm Park"));
		districtLineStations.add(new Station("EMB","Embankment"));
		districtLineStations.add(new Station("FBY","Fulham Broadway"));
		districtLineStations.add(new Station("GRD","Gloucester Road"));
		districtLineStations.add(new Station("GUN","Gunnersbury"));
		districtLineStations.add(new Station("HMD","Hammersmith"));
		districtLineStations.add(new Station("HST","High Street Kensington"));
		districtLineStations.add(new Station("HCH","Hornchurch"));
		districtLineStations.add(new Station("OLY","Kensington"));
		districtLineStations.add(new Station("KEW","Kew Gardens"));
		districtLineStations.add(new Station("MAN","Mansion House"));
		districtLineStations.add(new Station("MLE","Mile End"));
		districtLineStations.add(new Station("MON","Monument"));
		districtLineStations.add(new Station("OLY","Olympia"));
		districtLineStations.add(new Station("PGR","Parsons Green"));
		districtLineStations.add(new Station("PLW","Plaistow"));
		districtLineStations.add(new Station("PUT","Putney Bridge"));
		districtLineStations.add(new Station("RCP","Ravenscourt Park"));
		districtLineStations.add(new Station("RMD","Richmond"));
		districtLineStations.add(new Station("SSQ","Sloane Square"));
		districtLineStations.add(new Station("SKN","South Kensington"));
		districtLineStations.add(new Station("SFS","Southfields"));
		districtLineStations.add(new Station("SJP","St. James's Park"));
		districtLineStations.add(new Station("STB","Stamford Brook"));
		districtLineStations.add(new Station("STG","Stepney Green"));
		districtLineStations.add(new Station("TEM","Temple"));
		districtLineStations.add(new Station("THL","Tower Hill"));
		districtLineStations.add(new Station("TGR","Turnham Green"));
		districtLineStations.add(new Station("UPM","Upminster"));
		districtLineStations.add(new Station("UPB","Upminster Bridge"));
		districtLineStations.add(new Station("UPY","Upney"));
		districtLineStations.add(new Station("UPK","Upton Park"));
		districtLineStations.add(new Station("VIC","Victoria"));
		districtLineStations.add(new Station("WBT","West Brompton"));
		districtLineStations.add(new Station("WHM","West Ham"));
		districtLineStations.add(new Station("WKN","West Kensington"));
		districtLineStations.add(new Station("WMS","Westminster"));
		districtLineStations.add(new Station("WCL","Whitechapel"));
		districtLineStations.add(new Station("WDN","Wimbledon"));
		districtLineStations.add(new Station("WMP","Wimbledon Park"));
		map.put("D", districtLineStations);
		
		List<Station> hammersmithLineStations = new ArrayList<Station>();
		hammersmithLineStations.add(new Station("ALD","Aldgate"));
		hammersmithLineStations.add(new Station("ALE","Aldgate East"));
		hammersmithLineStations.add(new Station("BST","Baker Street"));
		hammersmithLineStations.add(new Station("BAR","Barbican"));
		hammersmithLineStations.add(new Station("BKG","Barking"));
		hammersmithLineStations.add(new Station("BLF","Blackfriars"));
		hammersmithLineStations.add(new Station("BWR","Bow Road"));
		hammersmithLineStations.add(new Station("BBB","Bromley-by-Bow"));
		hammersmithLineStations.add(new Station("CST","Cannon Street"));
		hammersmithLineStations.add(new Station("EHM","East Ham"));
		hammersmithLineStations.add(new Station("ERD","Edgware Road"));
		hammersmithLineStations.add(new Station("EMB","Embankment"));
		hammersmithLineStations.add(new Station("ESQ","Euston Square"));
		hammersmithLineStations.add(new Station("FAR","Farringdon"));
		hammersmithLineStations.add(new Station("GRD","Gloucester Road"));
		hammersmithLineStations.add(new Station("GPS","Great Portland Street"));
		hammersmithLineStations.add(new Station("HMS","Hammersmith"));
		hammersmithLineStations.add(new Station("HST","High Street Kensington"));
		hammersmithLineStations.add(new Station("KXX","King's Cross St Pancras"));
		hammersmithLineStations.add(new Station("LST","Liverpool Street"));
		hammersmithLineStations.add(new Station("MAN","Mansion House"));
		hammersmithLineStations.add(new Station("MLE","Mile End"));
		hammersmithLineStations.add(new Station("MON","Monument"));
		hammersmithLineStations.add(new Station("MGT","Moorgate"));
		hammersmithLineStations.add(new Station("PAD","Paddington"));
		hammersmithLineStations.add(new Station("PLW","Plaistow"));
		hammersmithLineStations.add(new Station("SSQ","Sloane Square"));
		hammersmithLineStations.add(new Station("SKN","South Kensington"));
		hammersmithLineStations.add(new Station("SJP","St. James's Park"));
		hammersmithLineStations.add(new Station("STG","Stepney Green"));
		hammersmithLineStations.add(new Station("TEM","Temple"));
		hammersmithLineStations.add(new Station("THL","Tower Hill"));
		hammersmithLineStations.add(new Station("UPK","Upton Park"));
		hammersmithLineStations.add(new Station("VIC","Victoria"));
		hammersmithLineStations.add(new Station("WHM","West Ham"));
		hammersmithLineStations.add(new Station("WMS","Westminster"));
		hammersmithLineStations.add(new Station("WCL","Whitechapel"));
		map.put("H", hammersmithLineStations);
		
		List<Station> jubileeLineStations = new ArrayList<Station>();
		jubileeLineStations.add(new Station("BST","Baker Street"));
		jubileeLineStations.add(new Station("BER","Bermondsey"));
		jubileeLineStations.add(new Station("BDS","Bond Street"));
		jubileeLineStations.add(new Station("CWR","Canada Water"));
		jubileeLineStations.add(new Station("CWF","Canary Wharf"));
		jubileeLineStations.add(new Station("CNT","Canning Town"));
		jubileeLineStations.add(new Station("CPK","Canons Park"));
		jubileeLineStations.add(new Station("DHL","Dollis Hill"));
		jubileeLineStations.add(new Station("FRD","Finchley Road"));
		jubileeLineStations.add(new Station("GPK","Green Park"));
		jubileeLineStations.add(new Station("KIL","Kilburn"));
		jubileeLineStations.add(new Station("KBY","Kingsbury"));
		jubileeLineStations.add(new Station("LON","London Bridge"));
		jubileeLineStations.add(new Station("NEA","Neasden"));
		jubileeLineStations.add(new Station("NGW","North Greenwich"));
		jubileeLineStations.add(new Station("QBY","Queensbury"));
		jubileeLineStations.add(new Station("SWK","Southwark"));
		jubileeLineStations.add(new Station("SJW","St John’s Wood"));
		jubileeLineStations.add(new Station("STA","Stanmore"));
		jubileeLineStations.add(new Station("SFD","Stratford"));
		jubileeLineStations.add(new Station("SWC","Swiss Cottage"));
		jubileeLineStations.add(new Station("WLO","Waterloo"));
		jubileeLineStations.add(new Station("WPK","Wembley Park"));
		jubileeLineStations.add(new Station("WHM","West Ham"));
		jubileeLineStations.add(new Station("WHD","West Hampstead"));
		jubileeLineStations.add(new Station("WMS","Westminster"));
		jubileeLineStations.add(new Station("WLG","Willesden Green"));
		map.put("J", jubileeLineStations);
		
		List<Station> metropolitanLineStations = new ArrayList<Station>();
		metropolitanLineStations.add(new Station("ALD","Aldgate"));
		metropolitanLineStations.add(new Station("AME","Amersham"));
		metropolitanLineStations.add(new Station("BST","Baker Street"));
		metropolitanLineStations.add(new Station("BAR","Barbican"));
		metropolitanLineStations.add(new Station("CLF","Chalfont and Latimer"));
		metropolitanLineStations.add(new Station("CWD","Chorleywood"));
		metropolitanLineStations.add(new Station("CLW","Colliers Wood"));
		metropolitanLineStations.add(new Station("CRX","Croxley"));
		metropolitanLineStations.add(new Station("ETE","Eastcote"));
		metropolitanLineStations.add(new Station("ESQ","Euston Square"));
		metropolitanLineStations.add(new Station("FAR","Farringdon"));
		metropolitanLineStations.add(new Station("FRD","Finchley Road"));
		metropolitanLineStations.add(new Station("GPS","Great Portland Street"));
		metropolitanLineStations.add(new Station("HOH","Harrow on the Hill"));
		metropolitanLineStations.add(new Station("HDN","Hillingdon"));
		metropolitanLineStations.add(new Station("ICK","Ickenham"));
		metropolitanLineStations.add(new Station("KXX","King's Cross St Pancras"));
		metropolitanLineStations.add(new Station("LST","Liverpool Street"));
		metropolitanLineStations.add(new Station("MPK","Moor Park"));
		metropolitanLineStations.add(new Station("MGT","Moorgate"));
		metropolitanLineStations.add(new Station("NHR","North Harrow"));
		metropolitanLineStations.add(new Station("NWP","Northwick Park"));
		metropolitanLineStations.add(new Station("NWD","Northwood"));
		metropolitanLineStations.add(new Station("NWH","Northwood Hills"));
		metropolitanLineStations.add(new Station("PIN","Pinner"));
		metropolitanLineStations.add(new Station("RLN","Rayners Lane"));
		metropolitanLineStations.add(new Station("RKY","Rickmansworth"));
		metropolitanLineStations.add(new Station("RUI","Ruislip"));
		metropolitanLineStations.add(new Station("RUM","Ruislip Manor"));
		metropolitanLineStations.add(new Station("UXB","Uxbridge"));
		metropolitanLineStations.add(new Station("WAT","Watford"));
		map.put("M", metropolitanLineStations);
		
		List<Station> northernLineStations = new ArrayList<Station>();
		northernLineStations.add(new Station("ANG","Angel"));
		northernLineStations.add(new Station("ARC","Archway"));
		northernLineStations.add(new Station("BAL","Balham"));
		northernLineStations.add(new Station("BNK","Bank"));
		northernLineStations.add(new Station("BPK","Belsize Park"));
		northernLineStations.add(new Station("BOR","Borough"));
		northernLineStations.add(new Station("BTX","Brent Cross"));
		northernLineStations.add(new Station("BUR","Burnt Oak"));
		northernLineStations.add(new Station("CTN","Camden Town"));
		northernLineStations.add(new Station("CHF","Chalk Farm"));
		northernLineStations.add(new Station("CHX","Charing Cross"));
		northernLineStations.add(new Station("CPC","Clapham Common"));
		northernLineStations.add(new Station("CPN","Clapham North"));
		northernLineStations.add(new Station("CPS","Clapham South"));
		northernLineStations.add(new Station("COL","Colindale"));
		northernLineStations.add(new Station("CLW","Colliers Wood"));
		northernLineStations.add(new Station("EFY","East Finchley"));
		northernLineStations.add(new Station("EDG","Edgware"));
		northernLineStations.add(new Station("ELE","Elephant and Castle"));
		northernLineStations.add(new Station("EMB","Embankment"));
		northernLineStations.add(new Station("EUS","Euston"));
		northernLineStations.add(new Station("FYC","Finchley Central"));
		northernLineStations.add(new Station("GGR","Golders Green"));
		northernLineStations.add(new Station("GST","Goodge Street"));
		northernLineStations.add(new Station("HMP","Hampstead"));
		northernLineStations.add(new Station("HND","Hendon Central"));
		northernLineStations.add(new Station("HBT","High Barnet"));
		northernLineStations.add(new Station("HIG","Highgate"));
		northernLineStations.add(new Station("KEN","Kennington"));
		northernLineStations.add(new Station("KTN","Kentish Town"));
		northernLineStations.add(new Station("KXX","King's Cross St Pancras"));
		northernLineStations.add(new Station("LSQ","Leicester Square"));
		northernLineStations.add(new Station("LON","London Bridge"));
		northernLineStations.add(new Station("MHE","Mill Hill East"));
		northernLineStations.add(new Station("MGT","Moorgate"));
		northernLineStations.add(new Station("MOR","Morden"));
		northernLineStations.add(new Station("MCR","Mornington Crescent"));
		northernLineStations.add(new Station("OLD","Old Street"));
		northernLineStations.add(new Station("OVL","Oval"));
		northernLineStations.add(new Station("SWM","South Wimbledon"));
		northernLineStations.add(new Station("STK","Stockwell"));
		northernLineStations.add(new Station("TBE","Tooting Bec"));
		northernLineStations.add(new Station("TBY","Tooting Broadway"));
		northernLineStations.add(new Station("TCR","Tottenham Court Road"));
		northernLineStations.add(new Station("TOT","Totteridge and Whetstone"));
		northernLineStations.add(new Station("TPK","Tufnell Park"));
		northernLineStations.add(new Station("WST","Warren Street"));
		northernLineStations.add(new Station("WLO","Waterloo"));
		northernLineStations.add(new Station("WFY","West Finchley"));
		northernLineStations.add(new Station("WSP","Woodside Park"));
		map.put("M", northernLineStations);
		
		List<Station> picadillyLineStations = new ArrayList<Station>();
		picadillyLineStations.add(new Station("ACT","Acton Town"));
		picadillyLineStations.add(new Station("ALP","Alperton"));
		picadillyLineStations.add(new Station("AGR","Arnos Grove"));
		picadillyLineStations.add(new Station("ARL","Arsenal"));
		picadillyLineStations.add(new Station("BCT","Barons Court"));
		picadillyLineStations.add(new Station("BOS","Boston Manor"));
		picadillyLineStations.add(new Station("BGR","Bounds Green"));
		picadillyLineStations.add(new Station("CRD","Caledonian Road"));
		picadillyLineStations.add(new Station("CFS","Cockfosters"));
		picadillyLineStations.add(new Station("COV","Covent Garden"));
		picadillyLineStations.add(new Station("ECM","Ealing Common"));
		picadillyLineStations.add(new Station("ECT","Earl’s Court"));
		picadillyLineStations.add(new Station("ETE","Eastcote"));
		picadillyLineStations.add(new Station("FPK","Finsbury Park"));
		picadillyLineStations.add(new Station("GRD","Gloucester Road"));
		picadillyLineStations.add(new Station("GPK","Green Park"));
		picadillyLineStations.add(new Station("HMD","Hammersmith"));
		picadillyLineStations.add(new Station("HTX","Hatton Cross"));
		picadillyLineStations.add(new Station("HTF","Heathrow Terminal 4"));
		picadillyLineStations.add(new Station("HRV","Heathrow Terminal 5"));
		picadillyLineStations.add(new Station("HRC","Heathrow Terminals 123"));
		picadillyLineStations.add(new Station("HDN","Hillingdon"));
		picadillyLineStations.add(new Station("HOL","Holborn"));
		picadillyLineStations.add(new Station("HRD","Holloway Road"));
		picadillyLineStations.add(new Station("HNC","Hounslow Central"));
		picadillyLineStations.add(new Station("HNE","Hounslow East"));
		picadillyLineStations.add(new Station("HNW","Hounslow West"));
		picadillyLineStations.add(new Station("HPC","Hyde Park Corner"));
		picadillyLineStations.add(new Station("ICK","Ickenham"));
		picadillyLineStations.add(new Station("KXX","King's Cross St Pancras"));
		picadillyLineStations.add(new Station("KNB","Knightsbridge"));
		picadillyLineStations.add(new Station("LSQ","Leicester Square"));
		picadillyLineStations.add(new Station("MNR","Manor House"));
		picadillyLineStations.add(new Station("NEL","North Ealing"));
		picadillyLineStations.add(new Station("NFD","Northfields"));
		picadillyLineStations.add(new Station("OAK","Oakwood"));
		picadillyLineStations.add(new Station("OST","Osterley"));
		picadillyLineStations.add(new Station("PRY","Park Royal"));
		picadillyLineStations.add(new Station("PIC","Piccadilly Circus"));
		picadillyLineStations.add(new Station("RLN","Rayners Lane"));
		picadillyLineStations.add(new Station("RUI","Ruislip"));
		picadillyLineStations.add(new Station("RUM","Ruislip Manor"));
		picadillyLineStations.add(new Station("RSQ","Russell Square"));
		picadillyLineStations.add(new Station("SEL","South Ealing"));
		picadillyLineStations.add(new Station("SHR","South Harrow"));
		picadillyLineStations.add(new Station("SKN","South Kensington"));
		picadillyLineStations.add(new Station("SGT","Southgate"));
		picadillyLineStations.add(new Station("SHL","Sudbury Hill"));
		picadillyLineStations.add(new Station("STN","Sudbury Town"));
		picadillyLineStations.add(new Station("TGR","Turnham Green"));
		picadillyLineStations.add(new Station("TPL","Turnpike Lane"));
		picadillyLineStations.add(new Station("UXB","Uxbridge"));
		picadillyLineStations.add(new Station("WGN","Wood Green"));
		map.put("P", picadillyLineStations);
		
		List<Station> victoriaLineStations = new ArrayList<Station>();
		victoriaLineStations.add(new Station("BHR","Blackhorse Road"));
		victoriaLineStations.add(new Station("BRX","Brixton"));
		victoriaLineStations.add(new Station("EUS","Euston"));
		victoriaLineStations.add(new Station("FPK","Finsbury Park"));
		victoriaLineStations.add(new Station("GPK","Green Park"));
		victoriaLineStations.add(new Station("HBY","Highbury and Is"));
		victoriaLineStations.add(new Station("KXX","King's Cross St"));
		victoriaLineStations.add(new Station("OXC","Oxford Circus"));
		victoriaLineStations.add(new Station("PIM","Pimlico"));
		victoriaLineStations.add(new Station("SVS","Seven Sisters"));
		victoriaLineStations.add(new Station("STK","Stockwell"));
		victoriaLineStations.add(new Station("TTH","Tottenham Hale"));
		victoriaLineStations.add(new Station("VUX","Vauxhall"));
		victoriaLineStations.add(new Station("VIC","Victoria"));
		victoriaLineStations.add(new Station("WAL","Walthamstow Cen"));
		victoriaLineStations.add(new Station("WST","Warren Street"));
		map.put("V", victoriaLineStations);
		
		List<Station> waterlooLineStations = new ArrayList<Station>();
		waterlooLineStations.add(new Station("BNK","Bank"));
		waterlooLineStations.add(new Station("WLO","Waterloo"));
		map.put("W", waterlooLineStations);
		
		return map;
    }
	

}
